module.exports = {
    name: 'test',
    description: 'test test',
    execute(message, args, Discord, client) {
        //code here
        let AvatarIcon = "https://cdn.discordapp.com/icons/795737290236100678/c19c7be2b6b74ece4ff6961551a1c73b.webp?size=128";
        const Embed = new Discord.MessageEmbed()
            .setColor("#FF00FF")
            .setTitle("Member List")
            .setURL('https://discord.gg/NyG7hHfMTV')
            .setAuthor('Venezuelan Hideout', AvatarIcon)
            .setDescription('----------------\n\n');
        //forloop to .addFields

            let Bots = message.guild.roles.cache.get('810947283910656001');
            let botmap = Bots.members.map(m => m.user.username);

            for(bots of botmap){
                Embed.addFields({
                    name: bots, value: '\u200B', inline: false},)
            }

            let Admins = message.guild.roles.cache.get('810943488186253352');
            let adminMap = Admins.members.map(m => m.user.username);
            for (admins of adminMap){
                Embed.addFields({
                    name: admins, value: '\u200B', inline: false},)
                }
    


        Embed.setImage(AvatarIcon)
            .setTimestamp()
            .setFooter('generated by VeneBot, in Development.');

        message.channel.send(Embed);


        //let Admin = message.guild.roles.cache.get('810943488186253352');
        //let Map = Admin.members.map(m => m.user.tag);

        //  for(users of Map){
        //    ListEmbed.addField(crown, users);
        //}


    }
}



