const moment = require('moment');
module.exports = {
    name: 'update',
    description: 'Updates memberlist',
    async execute(message, args, Discord, client) {
        const channel = message.guild.channels.cache.find(c => c.name === 'members');
        if(!channel) return message.channel.send("member-list channel not found.");
        if(message.channel.id != channel.id) return message.channel.send("Not allowed");
        
        message.delete();
        await message.channel.messages.fetch({ limit: 60 }).then(messages => {
            message.channel.bulkDelete(messages);
        });

        let date = moment().format("MM/DD/YY");
        let time = moment().format("hh:mm:ss A");
        
        let ClanRole = message.guild.roles.cache.find(r => r.name === 'member');
        let ClanMap = ClanRole.members.map(m => m.user.username);
        let Icon = "https://cdn.discordapp.com/icons/795737290236100678/c19c7be2b6b74ece4ff6961551a1c73b.webp?size=128";

        const NewEmbed = new Discord.MessageEmbed()
            .setColor('#FF00FF')
            .setTitle("Current Roster as of\n" + date + " \n" + time)
            .setURL('https://discord.gg/')
            .setAuthor('Venezuelan Hideout', Icon)
            .setDescription('----------------\n\n');

        var i;
        
        //THis is a testing loop here.
        for(i = 0; i < 40; i++){
            NewEmbed.addField("COOLGUY"+i, '\u200B', true);
        }

    /** for (clans of ClanMap) {
            NewEmbed.addFields({
                name: clans, value: '\u200B', inline: false
            })
        }*/

        /**for(clans of ClanMap) {
            NewEmbed.addField(clans, '\u200B', false);
        }*/

        NewEmbed.setImage(Icon)
        .setTimestamp()
        .setFooter('generated by VeneBot, in Development.');

       await message.channel.send(NewEmbed);

    }
}
